// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Srv.Model.DataContext;

#nullable disable

namespace TaskManager.Srv.Migrations
{
    [DbContext(typeof(ManagerContext))]
    [Migration("20231004080352_NameUnique")]
    partial class NameUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.CommentLine", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RowId")
                        .HasName("pk_comment_line");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_comment_line_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comment_line_user_id");

                    b.ToTable("comment_line", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ConnectingWiDb", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<int>("WiId")
                        .HasColumnType("int")
                        .HasColumnName("wi_id");

                    b.HasKey("RowId")
                        .HasName("pk_connecting_wi_db");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_connecting_wi_db_task_id");

                    b.HasIndex("WiId")
                        .HasDatabaseName("ix_connecting_wi_db_wi_id");

                    b.ToTable("connecting_wi_db", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.Project", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<Guid>("TechnicalName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("technical_name")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("RowId")
                        .HasName("pk_project");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_project_name");

                    b.HasIndex("TechnicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_project_technical_name");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ProjectTask", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("ProjectRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_row_id");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TechnicalName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("technical_name")
                        .HasDefaultValueSql("NEWID()");

                    b.HasKey("RowId")
                        .HasName("pk_project_task");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_project_task_name");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_task_project_id");

                    b.HasIndex("ProjectRowId")
                        .HasDatabaseName("ix_project_task_project_row_id");

                    b.HasIndex("TechnicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_project_task_technical_name");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_project_task_project_id_name");

                    b.ToTable("project_task", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ProjectUser", b =>
                {
                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("LastVisit")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_visit");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_user");

                    b.HasIndex("LastVisit")
                        .HasDatabaseName("ix_project_user_last_visit");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_user_user_id");

                    b.ToTable("project_user", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.TaskMilestone", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime?>("Actual")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual");

                    b.Property<long>("MilestoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("milestone_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Planned")
                        .HasColumnType("datetime2")
                        .HasColumnName("planned");

                    b.Property<long?>("ProjectTaskRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_task_row_id");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.HasKey("RowId")
                        .HasName("pk_task_milestone");

                    b.HasIndex("ProjectTaskRowId")
                        .HasDatabaseName("ix_task_milestone_project_task_row_id");

                    b.HasIndex("TaskId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_task_milestone_task_id_name");

                    b.ToTable("task_milestone", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.User", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_name");

                    b.HasKey("RowId")
                        .HasName("pk_user");

                    b.HasIndex("UserName")
                        .HasDatabaseName("ix_user_user_name");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.WiLinkTemplate", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assigned_to");

                    b.Property<int>("Iteration")
                        .HasColumnType("int")
                        .HasColumnName("iteration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("TeamProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("team_project");

                    b.Property<int>("WiType")
                        .HasColumnType("int")
                        .HasColumnName("wi_type");

                    b.HasKey("RowId")
                        .HasName("pk_wi_link_template");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_wi_link_template_project_id");

                    b.ToTable("wi_link_template", (string)null);
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.CommentLine", b =>
                {
                    b.HasOne("TaskManager.Srv.Model.DataModel.ProjectTask", "ProjectTask")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_line_project_task_project_task_temp_id");

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ProjectTask", b =>
                {
                    b.HasOne("TaskManager.Srv.Model.DataModel.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_task_project_project_id");

                    b.HasOne("TaskManager.Srv.Model.DataModel.Project", null)
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectRowId")
                        .HasConstraintName("fk_project_task_project_project_row_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ProjectUser", b =>
                {
                    b.HasOne("TaskManager.Srv.Model.DataModel.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_user_project_project_id");

                    b.HasOne("TaskManager.Srv.Model.DataModel.User", "User")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_user_user_user_temp_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.TaskMilestone", b =>
                {
                    b.HasOne("TaskManager.Srv.Model.DataModel.ProjectTask", null)
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectTaskRowId")
                        .HasConstraintName("fk_task_milestone_project_task_project_task_row_id");

                    b.HasOne("TaskManager.Srv.Model.DataModel.ProjectTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_milestone_project_task_task_id");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.WiLinkTemplate", b =>
                {
                    b.HasOne("TaskManager.Srv.Model.DataModel.Project", "Project")
                        .WithMany("WiLinkTemplates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wi_link_template_project_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.Project", b =>
                {
                    b.Navigation("ProjectTasks");

                    b.Navigation("ProjectUsers");

                    b.Navigation("WiLinkTemplates");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.ProjectTask", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("TaskManager.Srv.Model.DataModel.User", b =>
                {
                    b.Navigation("ProjectUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
